### PR TITLE
fix(plugins/container): avoid seg fault

### LINKED ISSUE #943: container plugin: segmentation violation when running on Falco with `-o base_syscalls.all=true`
**Describe the bug**

See the screenshot. 

**How to reproduce it**

Try 
```
sudo falco -o libs_logger.severity=trace -o libs_logger.enabled=true -o base_syscalls.all=true
```

Try it multiple times if the problem does not occur. There's likely a race condition under the hood.

**Expected behaviour**

**Screenshots**

```
Tue Aug 26 18:14:04 2025: [libs]: container: starting async go-worker
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x120 pc=0x7fc480ce0dfb]

goroutine 17 [running, locked to thread]:
github.com/falcosecurity/plugins/plugins/container/go-worker/pkg/container.(*dockerEngine).ctrToInfo(_, {_, _}, {0x0, {0x0, 0x0, 0x0}, 0x0, 0x0, 0x0})
        /home/leogr/code/github.com/falcosecurity/plugins/plugins/container/go-worker/pkg/container/docker.go:107 +0x5b
github.com/falcosecurity/plugins/plugins/container/go-worker/pkg/container.(*dockerEngine).List(0xc0002a0330, {0x7fc4815e5440, 0xc0004b2000})
        /home/leogr/code/github.com/falcosecurity/plugins/plugins/container/go-worker/pkg/container/docker.go:357 +0x41a
main.StartWorker(0x7fc47febe700, 0x7fc47f7fd800, 0x7ffe9ea582b8)
        /home/leogr/code/github.com/falcosecurity/plugins/plugins/container/go-worker/worker_api.go:77 +0x4f3
[1]    350927 IOT instruction  sudo falco -o libs_logger.severity=trace -o libs_logger.enabled=true -o
```

**Environment**

- Falco version:
```
Tue Aug 26 18:17:24 2025: Falco version: 0.41.3 (x86_64)
Tue Aug 26 18:17:24 2025: Falco initialized with configuration files:
Tue Aug 26 18:17:24 2025:    /etc/falco/config.d/falco.container_plugin.yaml | schema validation: ok
Tue Aug 26 18:17:24 2025:    /etc/falco/falco.yaml | schema validation: ok
Tue Aug 26 18:17:24 2025: System info: Linux version 6.16.3-arch1-1 (linux@archlinux) (gcc (GCC) 15.2.1 20250813, GNU ld (GNU Binutils) 2.45.0) #1 SMP PREEMPT_DYNAMIC Sat, 23 Aug 2025 15:32:49 +0000
Falco version: 0.41.3
Libs version:  0.21.0
Plugin API:    3.11.0
Engine:        0.50.0
Driver:
  API version:    8.0.0
  Schema version: 3.6.0
  Default driver: 8.1.0+driver
```
- System info:

- Cloud provider or hardware configuration:
- OS:

- Kernel:

- Installation method:

**Additional context**

I reproduced it both with plugin 0.3.3 and the latest dev version.

### PR DESCRIPTION
**Pull request by leogr**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area plugins

> /area registry

> /area build

> /area documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #943 

**Special notes for your reviewer**:

### CODE REVIEW

File: plugins/container/go-worker/pkg/container/cri.go [hunk 1]
```diff
@@ -378,6 +374,19 @@ func (c *criEngine) ctrToInfo(ctx context.Context, ctr *v1.ContainerStatus, podS
 			Size:             size,
 		},
 	}
+
+	if podSandboxStatus.Linux != nil && podSandboxStatus.Linux.Namespaces != nil &&
```
Comment (mstemm) [inline plugins/container/go-worker/pkg/container/cri.go:378]: I don't really know the context, but do you also need to check that podSandboxStatus is nil?

**Review by mstemm — CHANGES_REQUESTED** [review]
