### PR TITLE
fix(container): correct image parsing with registry port

### LINKED ISSUE #1139: bug(container): image/tag parsing fails for registries with port numbers
**Describe the bug**

Container image parsing is broken when the registry URL has a port number. The code splits on ALL colons with `strings.Split(image, ":")`, so it can't tell the difference between a registry port and an image tag.

This is the same bug as #825, which got auto-closed by the stale bot without being fixed.

**How to reproduce it**

1. Run a container with an image from a registry that has a port:
    ```bash
    docker run registry.example.com:5000/foo/bar:latest
    ```

2. Check Falco output for `container.image.repository` and `container.image.tag` fields

3. The values will be incorrect:
    - For `registry.example.com:5000/foo/bar:latest`:
      - Splits into 3 parts, fails `len == 2` check, leaves repo and tag empty
    - For `registry.example.com:5000/foo/bar`:
      - `container.image.repository = "registry.example.com"` (wrong - missing port and path)
      - `container.image.tag = "5000/foo/bar"` (wrong - port and path parsed as tag)

**Expected behaviour**

For `registry.example.com:5000/foo/bar:latest`:
- `container.image.repository = "registry.example.com:5000/foo/bar"`
- `container.image.tag = "latest"`

For `registry.example.com:5000/foo/bar`:
- `container.image.repository = "registry.example.com:5000/foo/bar"`
- `container.image.tag = ""` or `"latest"`

**Screenshots**

N/A

**Environment**

- Falco version: 0.42.1(plugins/container 0.4.1)
- System info: Ubuntu 22.04.5 LTS / containerd://2.1.5
- Cloud provider or hardware configuration:
- OS: Ubuntu
- Kernel: 5.15.0-157-generic
- Installation method: kubernetes with Falco helm chart

**Additional context**

**Affected code locations:**

The bug exists in 4 files in the plugins repository:
1. `plugins/container/go-worker/pkg/container/podman.go:109-112`
2. `plugins/container/go-worker/pkg/container/containerd.go:150-153`
3. `plugins/container/go-worker/pkg/container/cri.go:325-328`
4. `plugins/container/go-worker/pkg/container/docker.go:203-213`

All using the same broken pattern:
```go
imageRepoTag := strings.Split(image, ":")
if len(imageRepoTag) == 2 {
    imageRepo = imageRepoTag[0]
    imageTag = imageRepoTag[1]
}
```

**Verified in latest code:**

Static analysis confirms this bug still exists in the latest main branch of the plugins repository (as of 2025-12-18, commit `419e315`).

**Impact:**

This breaks for anyone using:
- Private registries with ports (`registry.company.com:5000/...`)
- Corporate registry setups
- Digest-based images

Wrong image/tag data can break security policies, audit logs, and allowlists.

**Proposed fix:**

Split on the LAST colon, not all colons:

```go
func splitImageAndTag(image string) (repo, tag string) {
    // Strip digest if present
    if idx := strings.Index(image, "@"); idx > 0 {
        image = image[:idx]
    }

    lastSlash := strings.LastIndex(image, "/")
    colonIdx := strings.LastIndex(image, ":")

    // Colon after last slash = tag separator
    if colonIdx > 0 && colonIdx > lastSlash {
        return image[:colonIdx], image[colonIdx+1:]
    }

    return image, ""
}
```

Or use an existing image reference parser like `github.com/distribution/reference`.

**Test cases that should pass:**
- `registry.example.com:5000/foo/bar:latest` → repo: `registry.example.com:5000/foo/bar`, tag: `latest`
- `registry.example.com:5000/foo/bar` → repo: `registry.example.com:5000/foo/bar`, tag: `""`
- `docker.io/library/alpine:3.20.3` → repo: `docker.io/library/alpine`, tag: `3.20.3`
- `alpine:3.20.3` → repo: `alpine`, tag: `3.20.3`
- `alpine` → repo: `alpine`, tag: `""`

### PR DESCRIPTION
**Pull request by suzutan**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area plugins

> /area registry

> /area build

> /area documentation

**What this PR does / why we need it**:

Fixes container image parsing when the registry URL contains a port number.

Previously, the code used `strings.Split(image, ":")` which incorrectly split on ALL colons, making it unable to distinguish between registry ports and image tags. For example:
- `registry.example.com:5000/foo/bar:latest` would fail parsing (3 parts, fails len==2 check)
- `registry.example.com:5000/foo/bar` would incorrectly parse `registry.example.com` as repo and `5000/foo/bar` as tag

This PR introduces a new `parseImageRepoTag` function that correctly parses image references by:
- Only splitting on the last colon that appears after the last slash
- Properly handling registry URLs with ports
- Maintaining backward compatibility with simple image references

The fix has been applied to all container runtime engines: Docker, Podman, containerd, and CRI.

**Which issue(s) this PR fixes**:

Fixes #1139

**Special notes for your reviewer**:

- This is the same bug as #825, which was auto-closed by the stale bot without being fixed
- Added comprehensive unit tests covering various image reference formats including:
  - Registry with port and tag
  - Registry with port without tag
  - Multi-level paths with registry ports
  - Digest-based images
- The parsing logic now correctly handles all edge cases mentioned in the issue

### CODE REVIEW

**Review by irozzo-1A — COMMENTED** [review]
LGTM overall, just a nit

File: plugins/container/go-worker/pkg/container/engine.go [hunk 1]
```diff
@@ -182,3 +182,44 @@ func parsePortBindingHostPort(port string) (uint16, error) {
...
+	// If there's no colon, or the colon appears before the last slash
+	// (meaning it's part of a registry port), then there's no tag
+	if lastColon == -1 || (lastSlash != -1 && lastColon < lastSlash) {
+		return image, ""
+	}
+
+	// Split at the last colon
+	if digestRef {
+		return image[:lastColon], ""
+	}
```
Comment (irozzo-1A) [inline plugins/container/go-worker/pkg/container/engine.go]: Why don't we return the tag in case we have both tag and digest?

```suggestion
```

File: plugins/container/go-worker/pkg/container/engine.go [hunk 2]
```diff
@@ -182,3 +182,44 @@ func parsePortBindingHostPort(port string) (uint16, error) {
...
+func parseImageRepoTag(image string) (repo, tag string) {
+	if image == "" {
+		return "", ""
+	}
+
+	digestRef := false
+	if at := strings.Index(image, "@"); at != -1 {
+		image = image[:at]
+		digestRef = true
+	}
```
Comment (irozzo-1A) [inline plugins/container/go-worker/pkg/container/engine.go]: See my previous comment:

```suggestion
	if at := strings.Index(image, "@"); at != -1 {
		image = image[:at]
	}
```

**Review by irozzo-1A — DISMISSED** [review]
/lgtm

**Comment by irozzo-1A** [comment]
@suzutan Thanks for your changes, could you please squash commits before I integrate?

**Comment by suzutan** [comment]
@irozzo-1A Thanks for reviewing! I've squash the commits.
